# Generated by Django 2.2.5 on 2019-09-21 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='transfer.Country'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='transfer.City'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='transfer.Country'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='transfer.Currency'),
        ),
    ]
