# Generated by Django 2.2.5 on 2019-09-22 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0002_auto_20190921_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='iso_code',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
