# Generated by Django 2.2.5 on 2019-09-22 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0005_auto_20190922_2038'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currency',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ('-transaction_time',)},
        ),
    ]
