# Generated by Django 2.2.5 on 2019-09-22 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0006_auto_20190922_2048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currency',
            name='iso_code',
        ),
    ]
