# Generated by Django 2.2.5 on 2019-09-22 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0007_remove_currency_iso_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currency',
            options={'ordering': ('iso_code',)},
        ),
        migrations.RenameField(
            model_name='currency',
            old_name='name',
            new_name='iso_code',
        ),
    ]
