# Generated by Django 2.2.5 on 2019-09-22 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0009_auto_20190922_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='iso_code',
            field=models.CharField(max_length=3, unique=True),
        ),
    ]
